# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\designer\SelectWord.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_diagSelectWord(object):
    def setupUi(self, diagSelectWord):
        diagSelectWord.setObjectName("diagSelectWord")
        diagSelectWord.resize(600, 400)
        diagSelectWord.setMinimumSize(QtCore.QSize(600, 400))
        diagSelectWord.setMaximumSize(QtCore.QSize(600, 400))
        diagSelectWord.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.labelField_in = QtWidgets.QLabel(diagSelectWord)
        self.labelField_in.setGeometry(QtCore.QRect(10, 10, 201, 16))
        self.labelField_in.setObjectName("labelField_in")
        self.cbField_in = QtWidgets.QComboBox(diagSelectWord)
        self.cbField_in.setGeometry(QtCore.QRect(220, 10, 261, 22))
        self.cbField_in.setObjectName("cbField_in")
        self.bSearch = QtWidgets.QPushButton(diagSelectWord)
        self.bSearch.setGeometry(QtCore.QRect(490, 10, 93, 28))
        self.bSearch.setObjectName("bSearch")
        self.bConfirm = QtWidgets.QPushButton(diagSelectWord)
        self.bConfirm.setEnabled(False)
        self.bConfirm.setGeometry(QtCore.QRect(490, 360, 93, 28))
        self.bConfirm.setObjectName("bConfirm")
        self.bCancel = QtWidgets.QPushButton(diagSelectWord)
        self.bCancel.setGeometry(QtCore.QRect(290, 360, 93, 28))
        self.bCancel.setObjectName("bCancel")
        self.listResults = QtWidgets.QListWidget(diagSelectWord)
        self.listResults.setEnabled(False)
        self.listResults.setGeometry(QtCore.QRect(10, 70, 581, 281))
        self.listResults.setWordWrap(True)
        self.listResults.setObjectName("listResults")
        self.pbSearch = QtWidgets.QProgressBar(diagSelectWord)
        self.pbSearch.setGeometry(QtCore.QRect(10, 40, 581, 23))
        self.pbSearch.setProperty("value", 0)
        self.pbSearch.setTextVisible(False)
        self.pbSearch.setObjectName("pbSearch")
        self.bSkip = QtWidgets.QPushButton(diagSelectWord)
        self.bSkip.setGeometry(QtCore.QRect(390, 360, 93, 28))
        self.bSkip.setObjectName("bSkip")

        self.retranslateUi(diagSelectWord)
        QtCore.QMetaObject.connectSlotsByName(diagSelectWord)

    def retranslateUi(self, diagSelectWord):
        _translate = QtCore.QCoreApplication.translate
        diagSelectWord.setWindowTitle(_translate("diagSelectWord", "Nihongo Companion"))
        self.labelField_in.setText(_translate("diagSelectWord", "Field to search on dictionary:"))
        self.bSearch.setText(_translate("diagSelectWord", "Search"))
        self.bConfirm.setText(_translate("diagSelectWord", "Confirm"))
        self.bCancel.setText(_translate("diagSelectWord", "Cancel"))
        self.bSkip.setText(_translate("diagSelectWord", "Skip"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    diagSelectWord = QtWidgets.QDialog()
    ui = Ui_diagSelectWord()
    ui.setupUi(diagSelectWord)
    diagSelectWord.show()
    sys.exit(app.exec_())
