# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\designer\SelectExamples.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_diagSelectExamples(object):
    def setupUi(self, diagSelectExamples):
        diagSelectExamples.setObjectName("diagSelectExamples")
        diagSelectExamples.resize(600, 400)
        diagSelectExamples.setMinimumSize(QtCore.QSize(600, 400))
        diagSelectExamples.setMaximumSize(QtCore.QSize(600, 400))
        diagSelectExamples.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.layoutWidget = QtWidgets.QWidget(diagSelectExamples)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 601, 401))
        self.layoutWidget.setObjectName("layoutWidget")
        self.vlAll = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.vlAll.setContentsMargins(5, 5, 5, 5)
        self.vlAll.setObjectName("vlAll")
        self.tExamples = QtWidgets.QTableWidget(self.layoutWidget)
        self.tExamples.setEnabled(False)
        self.tExamples.setMaximumSize(QtCore.QSize(9999, 9999))
        self.tExamples.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tExamples.setObjectName("tExamples")
        self.tExamples.setColumnCount(2)
        self.tExamples.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tExamples.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tExamples.setHorizontalHeaderItem(1, item)
        self.tExamples.verticalHeader().setVisible(False)
        self.vlAll.addWidget(self.tExamples)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.rbOverwrite = QtWidgets.QRadioButton(self.layoutWidget)
        self.rbOverwrite.setObjectName("rbOverwrite")
        self.buttonGroup = QtWidgets.QButtonGroup(diagSelectExamples)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.rbOverwrite)
        self.horizontalLayout_3.addWidget(self.rbOverwrite)
        self.rbAppend = QtWidgets.QRadioButton(self.layoutWidget)
        self.rbAppend.setObjectName("rbAppend")
        self.buttonGroup.addButton(self.rbAppend)
        self.horizontalLayout_3.addWidget(self.rbAppend)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.vlAll.addLayout(self.horizontalLayout_3)
        self.hlBottom = QtWidgets.QHBoxLayout()
        self.hlBottom.setObjectName("hlBottom")
        self.labelField_out = QtWidgets.QLabel(self.layoutWidget)
        self.labelField_out.setObjectName("labelField_out")
        self.hlBottom.addWidget(self.labelField_out)
        self.cbField_out = QtWidgets.QComboBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbField_out.sizePolicy().hasHeightForWidth())
        self.cbField_out.setSizePolicy(sizePolicy)
        self.cbField_out.setObjectName("cbField_out")
        self.hlBottom.addWidget(self.cbField_out)
        self.bCancel = QtWidgets.QPushButton(self.layoutWidget)
        self.bCancel.setObjectName("bCancel")
        self.hlBottom.addWidget(self.bCancel)
        self.bConfirm = QtWidgets.QPushButton(self.layoutWidget)
        self.bConfirm.setEnabled(False)
        self.bConfirm.setObjectName("bConfirm")
        self.hlBottom.addWidget(self.bConfirm)
        self.vlAll.addLayout(self.hlBottom)

        self.retranslateUi(diagSelectExamples)
        QtCore.QMetaObject.connectSlotsByName(diagSelectExamples)

    def retranslateUi(self, diagSelectExamples):
        _translate = QtCore.QCoreApplication.translate
        diagSelectExamples.setWindowTitle(_translate("diagSelectExamples", "Nihongo Companion"))
        item = self.tExamples.horizontalHeaderItem(0)
        item.setText(_translate("diagSelectExamples", "Japanese"))
        item = self.tExamples.horizontalHeaderItem(1)
        item.setText(_translate("diagSelectExamples", "English"))
        self.rbOverwrite.setText(_translate("diagSelectExamples", "Overwrite field"))
        self.rbAppend.setText(_translate("diagSelectExamples", "Append to field"))
        self.labelField_out.setText(_translate("diagSelectExamples", "Field to append to:"))
        self.bCancel.setText(_translate("diagSelectExamples", "Cancel"))
        self.bConfirm.setText(_translate("diagSelectExamples", "Confirm"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    diagSelectExamples = QtWidgets.QDialog()
    ui = Ui_diagSelectExamples()
    ui.setupUi(diagSelectExamples)
    diagSelectExamples.show()
    sys.exit(app.exec_())
