# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\designer\SelectWord.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_diagSelectWord(object):
    def setupUi(self, diagSelectWord):
        diagSelectWord.setObjectName("diagSelectWord")
        diagSelectWord.resize(600, 400)
        diagSelectWord.setMinimumSize(QtCore.QSize(600, 400))
        diagSelectWord.setMaximumSize(QtCore.QSize(600, 400))
        diagSelectWord.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.layoutWidget = QtWidgets.QWidget(diagSelectWord)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 601, 401))
        self.layoutWidget.setObjectName("layoutWidget")
        self.vlAll = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.vlAll.setContentsMargins(5, 5, 5, 5)
        self.vlAll.setObjectName("vlAll")
        self.hlTop = QtWidgets.QHBoxLayout()
        self.hlTop.setObjectName("hlTop")
        self.labelField_in = QtWidgets.QLabel(self.layoutWidget)
        self.labelField_in.setObjectName("labelField_in")
        self.hlTop.addWidget(self.labelField_in)
        self.cbField_in = QtWidgets.QComboBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbField_in.sizePolicy().hasHeightForWidth())
        self.cbField_in.setSizePolicy(sizePolicy)
        self.cbField_in.setObjectName("cbField_in")
        self.hlTop.addWidget(self.cbField_in)
        self.bSearch = QtWidgets.QPushButton(self.layoutWidget)
        self.bSearch.setObjectName("bSearch")
        self.hlTop.addWidget(self.bSearch)
        self.vlAll.addLayout(self.hlTop)
        self.pbSearch = QtWidgets.QProgressBar(self.layoutWidget)
        self.pbSearch.setProperty("value", 0)
        self.pbSearch.setTextVisible(False)
        self.pbSearch.setObjectName("pbSearch")
        self.vlAll.addWidget(self.pbSearch)
        self.listResults = QtWidgets.QListWidget(self.layoutWidget)
        self.listResults.setEnabled(False)
        self.listResults.setMinimumSize(QtCore.QSize(0, 281))
        self.listResults.setWordWrap(True)
        self.listResults.setObjectName("listResults")
        self.vlAll.addWidget(self.listResults)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.labelDict = QtWidgets.QLabel(self.layoutWidget)
        self.labelDict.setObjectName("labelDict")
        self.horizontalLayout.addWidget(self.labelDict)
        self.cbDict = QtWidgets.QComboBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbDict.sizePolicy().hasHeightForWidth())
        self.cbDict.setSizePolicy(sizePolicy)
        self.cbDict.setObjectName("cbDict")
        self.horizontalLayout.addWidget(self.cbDict)
        self.bCancel = QtWidgets.QPushButton(self.layoutWidget)
        self.bCancel.setObjectName("bCancel")
        self.horizontalLayout.addWidget(self.bCancel)
        self.bSkip = QtWidgets.QPushButton(self.layoutWidget)
        self.bSkip.setObjectName("bSkip")
        self.horizontalLayout.addWidget(self.bSkip)
        self.bConfirm = QtWidgets.QPushButton(self.layoutWidget)
        self.bConfirm.setEnabled(False)
        self.bConfirm.setObjectName("bConfirm")
        self.horizontalLayout.addWidget(self.bConfirm)
        self.vlAll.addLayout(self.horizontalLayout)

        self.retranslateUi(diagSelectWord)
        QtCore.QMetaObject.connectSlotsByName(diagSelectWord)

    def retranslateUi(self, diagSelectWord):
        _translate = QtCore.QCoreApplication.translate
        diagSelectWord.setWindowTitle(_translate("diagSelectWord", "Nihongo Companion"))
        self.labelField_in.setText(_translate("diagSelectWord", "Field to search on dictionary:"))
        self.bSearch.setText(_translate("diagSelectWord", "Search"))
        self.labelDict.setText(_translate("diagSelectWord", "Dictionary:"))
        self.bCancel.setText(_translate("diagSelectWord", "Cancel"))
        self.bSkip.setText(_translate("diagSelectWord", "Skip"))
        self.bConfirm.setText(_translate("diagSelectWord", "Confirm"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    diagSelectWord = QtWidgets.QDialog()
    ui = Ui_diagSelectWord()
    ui.setupUi(diagSelectWord)
    diagSelectWord.show()
    sys.exit(app.exec_())
