name: Generate addon zip

on:
  push:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Checkout LFS objects
        run: git lfs checkout
      - name: Zip and add artifact
        uses: actions/upload-artifact@v2
        with:
          name: anki-nihongo-companion
          path: |
            **/*.py
            **/*.json
            **/*.txt
            nihongo_companion/gui/icons/*
            LICENSE
