name: Generate Addon Zip

on:
  push:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Zip and as artifact
        uses: actions/upload-artifact@v2
        with:
          name: anki-nihongo-companion
          path: |
            **/*.py
            LICENSE
